#!/bin/sh -x

### NOT A WARNING: This script creates a Standard User ccapable of causing
### chaos, but probably not too much destruction.
###
### For destruction, please see: ./create-account-demogorgon

# http://apple.stackexchange.com/questions/82472/what-steps-are-needed-to-create-a-new-user-from-the-command-line

. /etc/rc.common

# Determine OS version
osvers=$(sw_vers -productVersion | awk -F. '{print $2}')
sw_vers=$(sw_vers -productVersion)

LastID=`dscl . -list /Users UniqueID | awk '{print $2}' | sort -n | tail -1`
NextID=$((LastID + 1))

dscl . create /Users/demo
dscl . create /Users/demo RealName "demo"
dscl . create /Users/demo hint "Password Hint"
dscl . create /Users/demo picture "/Library/User Pictures/Nature/Nest.tif"
dscl . passwd /Users/demo demo
dscl . create /Users/demo UniqueID $NextID
dscl . create /Users/demo PrimaryGroupID 20   # Standard User
#dscl . create /Users/demo PrimaryGroupID 80  # Admin User
dscl . create /Users/demo UserShell /usr/local/bin/bash
dscl . create /Users/demo NFSHomeDirectory /Users/demo
cp -R /System/Library/User\ Template/English.lproj /Users/demo
chown -R demo:staff /Users/demo

# https://derflounder.wordpress.com/2013/10/27/disabling-the-icloud-sign-in-pop-up-message-on-lion-and-later/
# https://github.com/rtrouton/rtrouton_scripts/tree/master/rtrouton_scripts/disable_apple_icloud_and_diagnostic_pop_ups
sudo -u demo defaults write com.apple.SetupAssistant DidSeeCloudSetup -bool TRUE
sudo -u demo defaults write com.apple.SetupAssistant GestureMovieSeen none
sudo -u demo defaults write com.apple.SetupAssistant LastSeenCloudProductVersion "${sw_vers}"

sudo -u demo ./caps-to-control.sh

# http://apple.stackexchange.com/questions/201671/how-can-i-delete-multiple-users-from-os-x-yosemite
#sudo dscl . delete /Users/demo ; sudo rm -rf /Users/demo
